
###Registro  de usuario 
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "prueba",
    "email": "ars@hm.com",
    "password": "1234567"
}


### Login sin conexion a BDD
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "prueba2",
    "email": "ars@hm.com",
    "password": "123456"
}   

### users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3NjA0MTAzNjcsImV4cCI6MTc2MDQxMDQyN30.Ik5tiQdFBwICZ0JaAWnHbcLEHv47QxJkswCsFXulEiI